name: Multi-Job Example

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello!"

  date-job:
    runs-on: ubuntu-latest
    needs: hello-job
    steps:
      - name: Show date
        run: date

  third-job:
    runs-on: ubuntu-latest
    needs: hello-job
    steps:
      - name: Say something from Job 3
        run: echo "This is job 3!"
