name: Multi-Job Example

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello!"

  date-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show date
        run: date
